name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/s3-stack.yaml \
            --stack-name retail-sales-stack

      - name: Install Dependencies
        run: |
          pip install pandas boto3

      - name: Upload CSV
        run: |
          python s1.py \
            --bucket retail-sales-demo-bucket-533267146744\
            --file retail_sales_dataset.csv \
            --key raw/retail_sales_dataset.csv \
            --region us-east-1
